name: Bug Report
description: "Report a bug"
body:
  - type: markdown
    attributes:
      value: |
        Before creating a new bug report, please check that there isn't already a similar issue.

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps To Reproduce"
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: false

  - type: dropdown
    attributes:
      label: "Self-hosted or Cloud?"
      options:
        - Self-Hosted
        - solidtime Cloud
        - Both

  - type: input
    attributes:
      label: "Version of solidtime: (for self-hosted)"
    validations:
      required: false

  - type: input
    attributes:
      label: "solidtime self-hosting guide: (for self-hosted)"
      description: "Did you use the official guide to self-host solidtime? If yes, which one?"
    validations:
      required: false
